### PR TITLE
Regarding #106

### PR DESCRIPTION
**Pull request by Rahuljagwani**
Actually browsers like chrome have disabled displaying custom messages on reload from sites (previously I thought it was possible but on doing some research I find this). They display their own messages instead. 
You can test it here: https://rahuljagwani.github.io/concore-editor/
@pradeeban

### CODE REVIEW

**Comment by pradeeban** [comment]
ok, close enough. Thanks for the fix. Merged.

**Comment by Rahuljagwani** [comment]
@pradeeban 
Thanks for merging.

I have somewhat tried to integrate the concore-editor with concore. You can check it here: https://rahuljagwani.github.io/concore-editor/.

To test:
1. Start the concore server
2. Upload directory on concore-editor from which graphml has to be merged.(example: sample from demo or sampleplot from example etc.)
3. open the graphml file to be build
4. Now click on 'build' (wait for sometime to let it build and execute other functions)

For now it is working for only valid directories and files and a lot of checks are pending and order of executing functions has to be done in certain order.

I just want to know, is this the sort of integration which is expected?
Give me feedback about it.

Thanks

**Comment by pradeeban** [comment]
The steps look good to me. 

But you did not include one step above. That is, starting the FRI. 

Is that something you forgot to improve in the steps (which is okay - you can go ahead and edit the steps above), or did you make some changes in FRI or concore-editor to make that manual FRI startup step unnecessary/obsolete? (which will be fantastic, but we never thought about that that far).

**Comment by Rahuljagwani** [comment]
> The steps look good to me.
> 
> But you did not include one step above. That is, starting the FRI.
> 
> Is that something you forgot to include in the steps (which is okay - you can go ahead and edit the steps above), or did you make some changes in FRI or concore-editor to make that manual FRI startup step unnecessary/obsolete? (which will be fantastic, but we never thought about that that far).

Actually this implementation works when in fri/server (python3 main.py) is called manually, which I have mentioned in step 1 (starting the concore server) .

Here I have just made changes in concore-editor's axios api calls to server by removing the hardcoding and putting the generic variable name in code, which works when Directory and graphmls are uploaded.
(For ex-
  Axios.post(`http://127.0.0.1:5000/build/${this.superState.uploadedDirName}fetch=${this.superState.graphs[this.superState.curGraphIndex].fileName.split('.')[0]}`)
            .then((res) => { // eslint-disable-next-line
                alert(res.data['message'])
            }).catch((err) => { // eslint-disable-next-line
                alert(err);
            });
)

Regarding the "changes in FRI or concore-editor to make that manual FRI startup step unnecessary/obsolete" , I thought in this direction and came to conclusion about its implementation that even though its possible but a lot configuration change has to be done in node modules as from frontend js which is browser code we have use it as a server-side code and certain features will be difficult to use. We can implement this later after researching more, till then let user call backend manually.

**Comment by pradeeban** [comment]
Ah, this is good enough. My bad that I quickly skimmed through and did not notice "FRI" in your comment. You are right at calling it the concore server (both are essentially the same).

**Pull request merged**
