### PR TITLE
Issue #59 fixed, sample urls added

### PR DESCRIPTION
**Pull request by Rahuljagwani**
As mentioned in the description of the issue, sample URLs are added to concore-editor. For now they are not working (as this is first step towards integration) as they have only demo name for directory, but not actual directory. URLs are taken from test.py as mentioned and in upcoming weeks browser based integration will be done for smooth experience of user.

### CODE REVIEW

**Review by pradeeban — APPROVED** [review]

**Comment by pradeeban** [comment]
Thanks, @Rahuljagwani, for yet another contribution! 

Please host your own forked version of concore-editor, following the "Deploying concore-editor in GitHub" section in the [concore-editor README](https://github.com/ControlCore-Project/concore-editor). Please also make sure to keep your hosted concore-editor instance updated with your own changes. That would allow us to confirm that your changes are working even before reviewing/testing your commits and merging your fixes to the concore-editor repository.

We have updated the project description with the above message also. Since you are already attempting this project, I thought of sharing here also so that you won't miss out on that.

**Comment by Rahuljagwani** [comment]
> Thanks, @Rahuljagwani, for yet another contribution!
> 
> Please host your own forked version of concore-editor, following the "Deploying concore-editor in GitHub" section in the [concore-editor README](https://github.com/ControlCore-Project/concore-editor). Please also make sure to keep your hosted concore-editor instance updated with your own changes. That would allow us to confirm that your changes are working even before reviewing/testing your commits and merging your fixes to the concore-editor repository.
> 
> We have updated the project description with the above message also. Since you are already attempting this project, I thought of sharing here also so that you won't miss out on that.

As per the instructions I just deployed my forked version of concore-editor. The link for the deployment is:
https://rahuljagwani.github.io/concore-editor/

**Comment by pradeeban** [comment]
Thank you, please let us know once this is ready for review.

**Comment by Rahuljagwani** [comment]
This PR is ready for review.
To test changes follow these steps:
1. Click on https://rahuljagwani.github.io/concore-editor/
2. Click on + icon in graph workspace and enter any demo project, author name and save it.
3. Create any demo graph by clicking on node.
4. After creating graph click on any of the server buttons.
For now it will alert user by showing error as network error in alert box as server URLs will work when proper and complete integration will be done.

**Comment by pradeeban** [comment]
@Rahuljagwani thanks for the pull request.

Your pull request handles the negative use case. How about a positive one when the study actually exists?

We can start with the sample hard-coded URL as mentioned in this issue report. (The full implementation to find the actual study and run it, is part of the actual GSoC as that needs a much larger effort).

So, to implement the positive use case, you load a folder from concore with studies. Let's stick to "demo" folder since we are hard coding things. Then, each action (build, run, ...) will be performed on the sample.graphml (you hard code demo/sample.graphml for the URLs). With the proper implementation, we will replace the hard-coded values with the actual study names, in the GSoC.

**Comment by Rahuljagwani** [comment]
> @Rahuljagwani thanks for the pull request.
> 
> Your pull request handles the negative use case. How about a positive one when the study actually exists?
> 
> We can start with the sample hard-coded URL as mentioned in this issue report. (The full implementation to find the actual study and run it, is part of the actual GSoC as that needs a much larger effort).
> 
> So, to implement the positive use case, you load a folder from concore with studies. Let's stick to "demo" folder since we are hard coding things. Then, each action (build, run, ...) will be performed on the sample.graphml (you hard code demo/sample.graphml for the URLs). With the proper implementation, we will replace the hard-coded values with the actual study names, in the GSoC.

Understood I thought that too have to be done in gsoc period as well. Therefore will be working on same for now.

**Comment by Rahuljagwani** [comment]
@pradeeban  
As mentioned by you, I have hardcoded the URLs for demo directory's sample.graphml and it is working fine.
But a little change has to be done in backend flask app before testing that is enabling the CORS policy otherwise it is not possible to establish connection between backend and frontend. 
It is only two line code change so should I change it directly (send PR) or create an issue in https://github.com/ControlCore-Project/concore/issues.
Please let me know if there are any other changes to be made before closing this issue.

**Pull request merged**
