### PR TITLE
Name and icon for restoring graph button changed

### PR DESCRIPTION
**Pull request by Rahuljagwani**
@pradeeban 
Can be tested here: https://rahuljagwani.github.io/concore-editor/

### CODE REVIEW

**Comment by pradeeban** [comment]
Perfect. Thanks.

**Comment by parteekcoder** [comment]
@Rahuljagwani Nice Icon, but I think its thickness is not consistent with other icons

**Comment by pradeeban** [comment]
@parteekcoder will make an excellent QA tester. :) I did not notice. But he is right. 
This is not urgent. But when you have time, please replace it with an icon that is the same size and thickness as the others.

**Comment by parteekcoder** [comment]
> @parteekcoder will make an excellent QA tester. :)

I didn't understand that @pradeeban

**Comment by pradeeban** [comment]
@parteekcoder, I was just complimenting your QA (Quality Assurance) capabilities. Thanks. :)

**Comment by parteekcoder** [comment]
> @parteekcoder, I was just complimenting your QA (Quality Assurance) capabilities. Thanks. :)

Thanks @pradeeban

**Pull request merged**
