### PR TITLE
Author fix

### PR DESCRIPTION
**Pull request by parteekcoder**
hey @pradeeban I am fixing issue #105

Here I am associating authorName with each graph instance not with a single superstate , which implemented as before

Currenty this PR is not completed because:

1. I am testing this
2. minimizing the file changes

when it is completed I will inform you , till then you can see the progress here https://parteekcoder.github.io/concore-editor/

### CODE REVIEW

**Comment by parteekcoder** [comment]
@pradeeban currently I am left with the problem of page reloading , I am thinking of that

**Comment by pradeeban** [comment]
That is great progress, @parteekcoder!

**Comment by parteekcoder** [comment]
> That is great progress, @parteekcoder!

thanks @pradeeban , 2 things are left on which I am working now

1. reloading  problem removes data 
2.  on saving graphml file it should also save their associated author name

**Comment by pradeeban** [comment]
No worries. This fix should help with the "Contribute" option project as a way to associate contributions with the actual authors.

I will also be mostly off next week. So if I do not reply timely to GitHub comments next week (and especially to testing), it is that.

**Comment by parteekcoder** [comment]
Hey @pradeeban the issues addressed in this PR:

1. Associating authorName with each graphML file
2. On saving storing `authorName` in the graphML file
3. On opeing a graphML file retrieving the `authorName` from the graphML file

Now the problem I left with is reloading issue which is also the issue with Saving graphML files

**Comment by parteekcoder** [comment]
the solution I am thinking is to update this information in local storage as concore-editor is doing to store the graphs

**Comment by parteekcoder** [comment]
Also find solution for that Problem, I will push all commits soon

**Comment by pradeeban** [comment]
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/ControlCore-Project/concore-editor/pull/115/conflicts) or the to resolve conflicts.
Conflicting files
src/toolbarActions/toolbarFunctions.js

I think you need a new PR. Otherwise, please resolve the conflicts here, @parteekcoder.

Let me know once I can test it in your deployment. After that, I will merge it.

**Comment by parteekcoder** [comment]
@pradeeban I want to check some more for this PR , So I will inform you when that is completed

**Comment by pradeeban** [comment]
Sounds good.

**Comment by parteekcoder** [comment]
I will deploy it shortly for you to test

**Comment by parteekcoder** [comment]
@pradeeban you can test here https://parteekcoder.github.io/concore-editor/

PLease do this steps before:
- close all the graphs
- Don't open the graphs that are not created by my editor (because they not contain authorName in them )
- Empty the localStorage for the editor

Things I would like you to test that I done:
- Create new graph 
- Reload the tab and now check the AuthorName by clicking `pencil icon`
- Create a new graph and save that , now open that graph from where it is saved , check its authorName
- If open any study that is not created by my editor , it may contain empty authorName which can be updated later

Rest I appreciate your testing reviews and update my PR accordingly

**Comment by pradeeban** [comment]
What will happen If I do not do these steps? Will it crash anything?

PLease do this steps before:

    close all the graphs
    Don't open the graphs that are not created by my editor (because they not contain authorName in them )
    Empty the localStorage for the editor

**Pull request merged**
