### PR TITLE
issue #71

### PR DESCRIPTION
**Pull request by parteekcoder**
I am creating pull requests in Dev branch as told

### CODE REVIEW

**Comment by parteekcoder** [comment]
hey @pradeeban this is my deployed version you can check here https://parteekcoder.github.io/concore-editor/

**Comment by pradeeban** [comment]
I tested this. This PR prevents valid files (for example, programs with no extensions) from opening too. You cannot easily assume which of the extensions are to be permitted. One option is to cherrypick and avoid which files must not be opened. For example, we know png, jpeg, and jpg must not be opened.

But honestly, you are spending too much time on an issue that does not bother our users in practice. (We don't have images hanging around in the programs directory in practice).

**Comment by parteekcoder** [comment]
> I tested this. This PR prevents valid files (for example, programs with no extensions) from opening too. You cannot easily assume which of the extensions are to be permitted. One option is to cherrypick and avoid which files must not be opened. For example, we know png, jpeg, and jpg must not be opened.
> 
> But honestly, you are spending too much time on an issue that does not bother our users in practice. (We don't have images hanging around in the programs directory in practice).

@pradeeban can you please tell me which program files are you uploading with no extension

**Comment by parteekcoder** [comment]
> I tested this. This PR prevents valid files (for example, programs with no extensions) from opening too. You cannot easily assume which of the extensions are to be permitted. One option is to cherrypick and avoid which files must not be opened. For example, we know png, jpeg, and jpg must not be opened.
> 
> But honestly, you are spending too much time on an issue that does not bother our users in practice. (We don't have images hanging around in the programs directory in practice).

@pradeeban can you please tell me which program files are you uploading with no extension

**Comment by pradeeban** [comment]
There could be scripts (sh) developed without an extension (Linux runs scripts with no extensions too). There is also a wide variety of languages we aim to support.

**Comment by parteekcoder** [comment]
> There could be scripts (sh) developed without an extension (Linux runs scripts with no extensions too). There is also a wide variety of languages we aim to support.

Ok understood , will I now tackle image files

**Comment by pradeeban** [comment]
What are the files you aim to exclude? An option is to exclude known extensions. For example, png, jpg, and jpeg. Other option is to actually check the content of the files to see whether they are binary or textual. But this approach is tricky since we also support compiled Matlab programs as programs (although they cannot be opened by the program editor).

I would suggest we keep the issue as "won't fix" for now.

**Comment by parteekcoder** [comment]
> What are the files you aim to exclude? An option is to exclude known extensions. For example, png, jpg, and jpeg. Other option is to actually check the content of the files to see whether they are binary or textual. But this approach is tricky since we also support compiled Matlab programs as programs (although they cannot be opened by the program editor).
> 
> I would suggest we keep the issue as "won't fix" for now.


Ok , for now shall we exclude image files to be opened and later on we can improve that

**Comment by pradeeban** [comment]
That sounds fair.

**Pull request closed without merging**
