### PR TITLE
disabling button

### PR DESCRIPTION
**Pull request by parteekcoder**
issue #125 

In progress

### CODE REVIEW

**Comment by parteekcoder** [comment]
addresses issue #125 #140

**Comment by parteekcoder** [comment]
@pradeeban you can check test here https://parteekcoder.github.io/concore-editor/

**Comment by parteekcoder** [comment]
hey @pradeeban As I have asked you before about the GSoC projects , I have a little confusion

I want to contribute in projects `[1] An Integrated CONTROL-CORE experience` Or `[10] A "contribute" action to concore studies.` As I have already made some PR which are merged 
And in future also try to figure out some bugs and improve the functionality , but I want to know what is actually required and which project would be better for me , as We are interacting and working with each other for a quiet long time since I started my contribution in Concore and Concore-editor , you can guide me 
I am interested in both these projects and can develop them during the GSoC period , As now the proposal time is coming nearer so I need some reviews from you 

It will be a great help if you can guide me regarding this

**Comment by pradeeban** [comment]
Personally, I see you have established your territory with [10] A "contribute" action to concore studies project well. You made the connections to the Share button, proposed a solution to make it work (which I discouraged you from pursuing since that is not as important for now), then followed up with the idea of how to use the contribute action to "share" instead (since we deactivate the share option). You should illustrate these discussions in your proposal too (perhaps with links to our discussions).

Please note all the projects are of equal importance to concore. Some more research-intensive, some more focus to implementation.

If you choose to apply to both project ideas, make sure to include your own preference order. We cannot guarantee we will respect those preference orders when we select one. (because we judge the contributor on whether they fit the project idea best). But that helps if you indeed plan to apply for more. Feel free to get back to me with more questions.

**Comment by parteekcoder** [comment]
please test this deployment so that I can deploy my `author-fixes` for you to test , which will also help in the `contribute` you said before

**Comment by parteekcoder** [comment]
> Personally, I see you have established your territory with [10] A "contribute" action to concore studies project well. You made the connections to the Share button, proposed a solution to make it work (which I discouraged you from pursuing since that is not as important for now), then followed up with the idea of how to use the contribute action to "share" instead (since we deactivate the share option). You should illustrate these discussions in your proposal too (perhaps with links to our discussions).
> 
> Please note all the projects are of equal importance to concore. Some more research-intensive, some more focus to implementation.
> 
> If you choose to apply to both project ideas, make sure to include your own preference order. We cannot guarantee we will respect those preference orders when we select one. (because we judge the contributor on whether they fit the project idea best). But that helps if you indeed plan to apply for more. Feel free to get back to me with more questions.

hi @pradeeban , I want to share my approch with you 
Can you please once see and correct me if anything wrong , you can check at https://www.figma.com/file/Lzt4Zsed2rc32EyQ4CE28l/Untitled?node-id=9%3A267&t=OH9Xt5gS8lNq5NvO-1  you will find a flowchart and a docs file link

**Comment by pradeeban** [comment]
@parteekcoder, that looks good to me! Nice work. Please share your full proposal draft with Mark and Me once it is ready. I am traveling until March 24th. So I will review the proposals more carefully only on or after March 24th.

**Comment by parteekcoder** [comment]
Thanks @pradeeban for reviewing this approach , sure I will share proposal on 24 or after it 

Is there anything you would like to mention regarding this, I will be glad to hear

**Comment by pradeeban** [comment]
Make sure to highlight your past contributions to both concore and concore editor, and highlight how the GSoC project will also likely touch both concore and concore editor, and your approach/contributions to both.

**Comment by parteekcoder** [comment]
I have less contributions to concore but have a lot of contributions to concore-editor , Will that effect my proposal

**Comment by pradeeban** [comment]
@parteekcoder No, not at all. This project involves both concore and concore editor. As such, your overall contributions matter more than individual ones.

**Comment by parteekcoder** [comment]
> @parteekcoder No, not at all. This project involves both concore and concore editor. As such, your overall contributions matter more than individual ones.

thanks for clarification

I am not able to find other mentors on github for communication

**Comment by pradeeban** [comment]
You can email your draft proposal to the mentors. CC' me.

**Comment by parteekcoder** [comment]
> You can email your draft proposal to the mentors. CC' me.

sure as you are now busy in travelling I will send it to you on 25 march

**Comment by pradeeban** [comment]
Sounds good. Feel free to send it earlier as well (whenever it is ready - make sure to send a complete draft). Just remind me again on the 25th to look at it.

**Pull request merged**
