### PR TITLE
issue #101 fixed (again solved)

### PR DESCRIPTION
**Pull request by Rahuljagwani**
@pradeeban 
Sorry for previous PR. I have fixed the changes you mentioned in PR #102.
It can be tested here: https://rahuljagwani.github.io/concore-editor/

But there is one more issue that whether or not the graph displayed is created by user or uploaded, when browser reload happens 
then again the error "Switch to edge/Chrome" appears when clicked on Save Button.
I will create a separate issue for this and try to send a PR. (Its an existing issue even now)

### CODE REVIEW

**Comment by pradeeban** [comment]
This is neat. I had conflicting opinions on the Alert you introduced.
alert('File saved Successfully');

But I am more with you that previously without this alert, we were not sure whether the "Save" worked or not, especially with #58 appearing at times.

So I will merge this commit as is.

**Comment by Rahuljagwani** [comment]
> This is neat. I had conflicting opinions on the Alert you introduced. alert('File saved Successfully');
> 
> But I am more with you that previously without this alert, we were not sure whether the "Save" worked or not, especially with #58 appearing at times.
> 
> So I will merge this commit as is.

Can u please elaborate about the conflictions with alert('File saved Successfully') ??

**Comment by pradeeban** [comment]
> Can u please elaborate about the conflictions with alert('File saved Successfully') ??

Oh, this is a new Alert you have introduced. I usually dislike chatty messages that expect you to click "OK" or respond to continue working. But such notification is nice on this occasion as previously we had no clue whether the "Save" was properly executed or not (prompting us to click "Save" twice or thrice, "just in case". The animation for the Save button (or any buttons) to show they were clicked is weak in concore editor.

**Comment by Rahuljagwani** [comment]
> > Can u please elaborate about the conflictions with alert('File saved Successfully') ??
> 
> Oh, this is a new Alert you have introduced. I usually dislike chatty messages that expect you to click "OK" or respond to continue working. But such notification is nice on this occasion as previously we had no clue whether the "Save" was properly executed or not (prompting us to click "Save" twice or thrice, "just in case.") The animation for the Save button (or any buttons) to show they were clicked is weak in concore editor.

Yes, it can be irritating to give responses in form of clicks for users. In future we can use a [spinner + check mark] ( just like what github shows while performing checks on PRs ) or a notification to show file saved successfully. In that case user will not have to click buttons to respond.

**Comment by pradeeban** [comment]
Yes, those are good suggestions.

**Comment by parteekcoder** [comment]
@pradeeban is this change is in production

**Pull request merged**
