### PR TITLE
issue uploading image and binary files

### PR DESCRIPTION
**Pull request by parteekcoder**
issue #71 
@pradeeban As you told created separate PR for this issue
Added a check before opening files

### CODE REVIEW

**Comment by pradeeban** [comment]
Can you please deploy this to https://parteekcoder.github.io/concore-editor/ where I can quickly test it?

**Comment by parteekcoder** [comment]
> Can you please deploy this to https://parteekcoder.github.io/concore-editor/ where I can quickly test it?

ok @pradeeban

**Comment by parteekcoder** [comment]
@pradeeban now you can check at https://parteekcoder.github.io/concore-editor/

**Comment by pradeeban** [comment]
neat. thanks.

**Pull request merged**
