### PR TITLE
frontend of Contribute Feature

### PR DESCRIPTION
**Pull request by parteekcoder**

### CODE REVIEW

**Comment by parteekcoder** [comment]
Hi @pradeeban ,

I want to ask something could you please add me as a member of the organization because I want to test that I can create PRs from my account (say bot account)? I know in the last meeting you informed me that we can push the code to the wrong place by mistake but I ensure you I will only work with my forks and not directly push code to main repos. After I have tested u can revoke the membership .

Thanks for the consideration

**Comment by pradeeban** [comment]
We want you to have a third repository and create a PR from that repository to yours.

So, it will be a third github, bot account, parteekbot -> parteekcoder.

We discussed the rationale behind this approach last week. Perhaps, due to poor Internet, you did not catch that.

In this approach, parteekcoder will be like the CONTROL-CORE. As we discussed last week, please reach out to @Rahuljagwani first to make sure you start from where he left off. That way, his contributions so far won't be wasted (and you can contribute to his project too, when you have contributions).

**Comment by pradeeban** [comment]
We can discuss this Wednesday again, if something is not clear.

**Comment by parteekcoder** [comment]
> We can discuss this Wednesday again, if something is not clear.

yeah sure

**Comment by pradeeban** [comment]
That is awesome! Let's discuss on Wednesday!

**Pull request merged**
