### PR TITLE
Solved Save function

### PR DESCRIPTION
**Pull request by parteekcoder**
Hey @pradeeban  ,

Now Save function works even when we try to save new files which is not working before 
I removed that warning code which I added "directory="true" "

Now if there is Anything you would like to change please tell me

### CODE REVIEW

**Comment by parteekcoder** [comment]
Please see last commit changes

**Comment by pradeeban** [comment]
The "Save" function was working fine, but only in Edge or Chrome. Hence the warning message indicating to switch to Edge/Chrome.

Do you mean this PR fixes the "Save" function for other broswers?

Please mention which browsers this was tested on.

**Comment by parteekcoder** [comment]
Wait i will revert you about this

**Comment by parteekcoder** [comment]
Actually the issue is that safari doesnot support any option to showSaveFile , so the only option we are left with firefox is that it provides the feature that it install file in the last saved directory 

Actually this is requested that firefox would provide this feature

**Comment by pradeeban** [comment]
Ok, I will keep the PR on hold as currently, concore-editor only support Edge and Chrome.

**Comment by parteekcoder** [comment]
> The "Save" function was working fine, but only in Edge or Chrome. Hence the warning message indicating to switch to Edge/Chrome.
> 
> Do you mean this PR fixes the "Save" function for other broswers?
> 
> Please mention which browsers this was tested on.

It gives the above error in chrome and firefox
Above pic is of chrome browser

**Pull request closed without merging**
