### PR TITLE
corrected mistake

### PR DESCRIPTION
**Pull request by parteekcoder**
fixed issue #119 

Corrected typo error in reducer @pradeeban please review

### CODE REVIEW

**Comment by pradeeban** [comment]
@Rahuljagwani, can you please review this?
 
I am not a Javascript expert. I only test for functionality most of the time.

Please feel free to constructively review each other's (and other people's) code contributions. It is an open-source project, after all. We appreciate both of your contributions.

**Comment by Rahuljagwani** [comment]
> @Rahuljagwani, can you please review this?
> 
> I am not a Javascript expert. I only test for functionality most of the time.
> 
> Please feel free to constructively review each other's (and other people's) code contributions. It is an open-source project, after all. We appreciate both of your contributions.

Sure @pradeeban, I will review it in sometime.

**Review by Rahuljagwani — APPROVED** [review]

**Comment by Rahuljagwani** [comment]
@pradeeban this can be merged.
The code written by @parteekcoder is neat. I tested it, its working fine.

**Comment by pradeeban** [comment]
Thanks for the great team work in making the CONTROL-CORE code better, @parteekcoder and @Rahuljagwani.

**Comment by parteekcoder** [comment]
@pradeeban thanks for your comment and @Rahuljagwani for reviewing this PR

**Comment by parteekcoder** [comment]
Yeah the team work is great , In the future also we both will try to improve Concore-editor functionality and make it  more robust

**Comment by parteekcoder** [comment]
Yeah the team work is great , In the future also we both will try to improve Concore-editor functionality and make it  more robust

**Pull request merged**
